openapi: 3.0.0
info:
  title: P and P Hotels - Housekeeping App
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /publicrole/authmodule/login:
    post:
      summary: Login
      tags:
        - PublicRole
        - AuthModule
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./common/models/BaseResponse.v1.yaml
              examples:
                OK:
                  value:
                    id: 1000
                    status: '1'
                    errors: []
                    details:
                      access_token: '3rewteerserxhdsthstdy.asezasertsr.a35w345436!esszgknzleskg_90'
                      refresh_token: 123434346eye5
                      expiry_time_seconds: 3200
                Error:
                  value:
                    id: 0
                    status: '0'
                    errors:
                      - field_name: user_code
                        message_code: 'Login_Status: Invalid'
                      - field_name: user_pin
                        message_code: Required
                    details: null
      operationId: post-publicrole-authmodule-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_code:
                  type: string
                user_pin:
                  type: string
              required:
                - user_code
                - user_pin
            examples:
              Valid:
                value:
                  user_code: user@email.com
                  user_pin: '1234'
        description: ''
components:
  schemas: {}
  securitySchemes: {}
security: []
