openapi: 3.0.0
info:
  title: Auth Module
  version: '1.0'
  description: Backend APIs for Room Attendant app
servers:
  - url: 'https://pandp-housekeepingapp-v1.api.avamae.co.uk/api/v1'
    description: Public
paths:
  /publicrole/authmodule/login:
    post:
      summary: Login
      tags:
        - AuthModule
        - PublicRole
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./common/models/BaseResponse.v1.yaml
              examples:
                OK:
                  value:
                    id: 1000
                    status: '1'
                    errors: []
                    details:
                      access_token: '3rewteerserxhdsthstdy.asezasertsr.a35w345436!esszgknzleskg_90'
                      refresh_token: 123434346eye5
                      expiry_time_seconds: 3200
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./common/models/BaseResponse.v1.yaml
              examples:
                Error:
                  value:
                    id: 0
                    status: '0'
                    errors:
                      - field_name: user_code
                        message_code: 'Login_Status: Invalid'
                      - field_name: user_pin
                        message_code: Required
                    details: null
      operationId: post-publicrole-authmodule-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              minProperties: 2
              maxProperties: 2
              properties:
                user_code:
                  type: string
                  example: andrew.savory@avamae.co.uk
                user_pin:
                  type: string
                  pattern: '^[0-9]+$'
                  maxLength: 4
                  minLength: 4
                  example: '7894'
              required:
                - user_code
                - user_pin
            examples:
              Valid:
                value:
                  user_code: user@email.com
                  user_pin: '1234'
        description: ''
      description: |-
        Log in a user.

        Possible list of values returned for messageCode :
        Required: Need to supply a value

        Login_Status: Invalid => entered credentials are invalid

        Login_Status: Suppressed => User account is suppressed
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Bearer Auth:
      type: http
      scheme: bearer
