openapi: 3.0.0
info:
  title: Auth
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /publicrole/authmodule/login:
    post:
      summary: Login
      tags:
        - Auth
        - PublicRole
      responses: {}
      operationId: post-publicrole-authmodule-login
components:
  schemas: {}
